{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app.fullname" . }}
type: Opaque
  {{- with .Values.secrets }}
data:
  {{- range $key, $value := . }}
    {{- $key | nindent 2 }}: {{$value | toString | b64enc | quote}}
    {{- end}}
    {{- end }}
{{- end }}
